version: '3.8'

services:
  # 🐘 PostgreSQL
  postgres:
    image: postgres:latest
    container_name: friendflow-postgres
    environment:
      POSTGRES_USER: haxxu
      POSTGRES_PASSWORD: User123
      POSTGRES_DB: friendflow
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 🔁 ScyllaDB (Optional)
  # scylla:
  #   image: scylladb/scylla:latest
  #   container_name: scylla
  #   ports:
  #     - '9042:9042'

  # ☁️ MinIO
  minio:
    image: minio/minio
    container_name: friendflow-minio
    ports:
      - '9000:9000' # S3 API
      - '9001:9001' # Web UI
    environment:
      MINIO_ROOT_USER: haxxu
      MINIO_ROOT_PASSWORD: User1234
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  pgdata:
  minio-data:
