[request_definition]
r = sub, obj, act, ctx

[policy_definition]
p = sub, obj, act, eft, ctx

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == alow))

[matchers]
m = r.sub == p.sub && r.obj == p.obj && r.act == p.act && r.ctx == p.ctx
